[template]
src = "traefik.tmpl.toml"
dest = "traefik.toml"
prefix = "traefik"
keys = [
  "/acme/email",
  "/acme/enable",
  "/acme/entrypoint",
  "/acme/onhostrule",
  "/acme/storage",
  "/api/address",
  "/api/compression",
  "/api/dashboard",
  "/api/debug",
  "/api/enable",
  "/api/port",
  "/datadog/address",
  "/datadog/pushinterval",
  "/debug",
  "/default/entrypoints",
  "/grace/timeout",
  "/healthcheck/interval",
  "/insecure/skip",
  "/log/level",
  "/file/name",
  "/file/watch",
  "/http/address",
  "/http/compression",
  "/http/port",
  "/https/address",
  "/https/enable",
  "/https/compression",
  "/https/port",
  "/idle/timeout",
  "/influxdb/address",
  "/influxdb/pushinterval",
  "/k8s/ca",
  "/k8s/disable/pass/host/headers",
  "/k8s/enable",
  "/k8s/enable/pass/tls/cert",
  "/k8s/endpoint",
  "/k8s/filename",
  "/k8s/ingress/class",
  "/k8s/labelselector",
  "/k8s/namespaces",
  "/k8s/token",
  "/marathon/dcos/token",
  "/marathon/dialer/timeout",
  "/marathon/domain",
  "/marathon/enable",
  "/marathon/endpoint",
  "/marathon/expose",
  "/marathon/force/task/hostname",
  "/marathon/groups/as/subdomains",
  "/marathon/keep/alive",
  "/marathon/lb/compatibility",
  "/marathon/respect/readiness/checks",
  "/marathon/watch",
  "/mesos/domain",
  "/mesos/enable",
  "/mesos/endpoint",
  "/mesos/expose",
  "/mesos/filename",
  "/mesos/groups/as/subdomains",
  "/mesos/ip/sources",
  "/mesos/refresh",
  "/mesos/watch",
  "/mesos/zk/timeout",
  "/ping/address",
  "/ping/enable",
  "/ping/port",
  "/prometheus/buckets",
  "/prometheus/entrypoint",
  "/rancher/cattle/url",
  "/rancher/cattle/access/key",
  "/rancher/cattle/secret/key",
  "/rancher/domain",
  "/rancher/enable",
  "/rancher/expose",
  "/rancher/filename",
  "/rancher/healthcheck",
  "/rancher/intervalpoll",
  "/rancher/method",
  "/rancher/refresh",
  "/rancher/watch",
  "/read/timeout",
  "/statistics/recent/errors",
  "/statsd/address",
  "/statsd/pushinterval",
  "/write/timeout",
]
